### ISSUE TITLE
npm install Centos 7 dependency issues

### ISSUE THREAD

**Issue by wer** [jedireza/aqua#14]
** NPM INSTALL **

```
[root@development aqua]# npm install
npm WARN package.json aqua@2.0.1 No repository field.
npm WARN package.json handlebars@3.0.0 No README data
npm WARN unmet dependency /var/www/node/aqua/node_modules/lab requires handlebars@'2.x.x' but will load
npm WARN unmet dependency /var/www/node/aqua/node_modules/handlebars,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /var/www/node/aqua/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/glob requires graceful-fs@'~1.2.0' but will load
npm WARN unmet dependency /var/www/node/aqua/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.6
npm WARN unmet dependency /var/www/node/aqua/node_modules/gulp-less/node_modules/accord/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /var/www/node/aqua/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /var/www/node/aqua/node_modules/jsdom/node_modules/request requires qs@'~2.3.1' but will load
npm WARN unmet dependency /var/www/node/aqua/node_modules/qs,
npm WARN unmet dependency which is version 2.4.1
```

** NPM RUN SETUP **

```
[root@development aqua]# npm run setup

> aqua@2.0.1 setup /var/www/node/aqua
> ./setup.js

module.js:338
    throw err;
          ^
Error: Cannot find module './commands/insert_command'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/node/aqua/node_modules/mongodb/lib/mongodb/collection.js:5:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 3.10.0-123.8.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! aqua@2.0.1 setup: `./setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aqua@2.0.1 setup script './setup.js'.
npm ERR! This is most likely a problem with the aqua package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./setup.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls aqua
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/node/aqua/npm-debug.log
```

**Comment by jedireza** [comment]
Thanks for opening an issue.

`$ npm run setup` failing wouldn't surprise me though if the `$ npm install` step failed. So we'll need to figure that out first.

I don't have a lot of time to test with Centos7. I'll leave the issue open for a couple days. If you uncover more details, post them here.

**Comment by jedireza** [comment]
Any updates?

**Comment by jedireza** [comment]
Closing for now. Please post again if you find more details.
