### ISSUE TITLE
Error when viewing Index

### ISSUE THREAD

**Issue by HE-is** [jedireza/aqua#250]
I'm not quite sure what I'm missing, sorry to bother again with a diminutive noob question.
I have tried to deploy to my production vps host, which is Ubuntu 16.04. Everything installs fine (pertaining to nodejs) as far as I can tell. When I try to navigate to the index, it gives me this error:
```
Debug: internal, implementation, error 
    SyntaxError: /home/test/aqua/server/web/home/index.jsx: Unexpected token (10:21)
   8 |     render() {
   9 | 
> 10 |         const neck = <link rel='stylesheet' href="/public/pages/home.min.css" />;
     |                      ^
  11 | 
  12 |         return (
  13 |             <Layout
    at Parser.pp$5.raise (/home/test/aqua/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/test/aqua/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/test/aqua/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/home/test/aqua/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/test/aqua/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/test/aqua/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/test/aqua/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/test/aqua/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$1.parseVar (/home/test/aqua/node_modules/babylon/lib/index.js:2340:24)
    at Parser.pp$1.parseVarStatement (/home/test/aqua/node_modules/babylon/lib/index.js:2169:8)
```

Is this something to do with JSX not being accepted? (babel?) 
Thanks in advance! ^_^

**Comment by jedireza** [comment]
You probably don't have dev dependencies installed.

https://github.com/jedireza/aqua#running-in-production

> `NPM_CONFIG_PRODUCTION=false` - This tells `$ npm install` to not skip installing `devDependencies`, which we need to build the front-end files.

**Comment by HE-is** [comment]
I've attempted to set the environment variables through "export NPM_CONFIG_PRODUCTION=false" and putting them in /etc/environment. but I still end up with that error. Am I setting it correctly?

**Comment by jedireza** [comment]
After you set that you'll need to `$ npm install` again.

**Comment by HE-is** [comment]
Thanks! Working now!! ^_^
