### ISSUE TITLE
Problem when running aqua

### ISSUE THREAD

**Issue by teheavy** [jedireza/aqua#267]
Hi there,

I have been trying to setup aqua on my system, but it seems I cannot access http://127.0.0.1:8000/, mongod was running and I have tested on both Ubuntu and MacOS, all had the same problem.

Here's a log I got when I'm start running aqua

```
[13:15:50] Using gulpfile ~/aqua/gulpfile.js
[13:15:50] Starting 'watch'...
[13:15:50] Finished 'watch' after 44 ms
[13:15:50] Starting 'less'...
[13:15:50] Finished 'less' after 15 ms
[13:15:50] Starting 'webpack'...
[13:15:50] Starting 'media'...
[13:15:50] Starting 'nodemon'...
[13:15:50] Finished 'nodemon' after 143 ms
[13:15:50] [nodemon] 1.12.1
[13:15:50] [nodemon] to restart at any time, enter `rs`
[13:15:50] [nodemon] watching: *.*
[13:15:50] [nodemon] starting `node --inspect server.js`
node: bad option: --inspect
[13:15:51] [nodemon] app crashed - waiting for file changes before starting...
[13:15:54] Finished 'media' after 3.75 s
[13:16:03] [webpack] Hash: 42fdcdc83743d39e04f5
Version: webpack 3.8.1
Time: 13221ms
             Asset     Size  Chunks                    Chunk Names
      admin.min.js   854 kB       0  [emitted]  [big]  admin
    account.min.js   528 kB       1  [emitted]  [big]  account
       main.min.js   151 kB       2  [emitted]         main
    ../core.min.js   972 kB       3  [emitted]  [big]  core
  admin.min.js.map   997 kB       0  [emitted]         admin
account.min.js.map   647 kB       1  [emitted]         account
   main.min.js.map   154 kB       2  [emitted]         main
../core.min.js.map  1.15 MB       3  [emitted]         core
  [34] (webpack)/buildin/module.js 495 bytes {3} [built]
 [193] ./node_modules/react-dom/index.js 59 bytes {3} [built]
 [293] ./client/pages/account/index.jsx 1.29 kB {1} [built]
 [294] ./client/pages/account/app.jsx 983 bytes {1} [built]
 [455] ./client/pages/admin/index.jsx 400 bytes {0} [built]
 [456] ./client/pages/admin/app.jsx 2.46 kB {0} [built]
 [495] ./client/pages/admin/admins/search/index.jsx 6.14 kB {0} [built]
 [501] ./client/pages/admin/footer.jsx 3.36 kB {0} [built]
 [502] ./client/pages/admin/home/index.jsx 9.65 kB {0} [built]
 [503] ./client/pages/admin/navbar.jsx 7.68 kB {0} [built]
 [504] ./client/pages/admin/not-found.jsx 2.71 kB {0} [built]
 [505] ./client/pages/admin/statuses/details/index.jsx 5.82 kB {0} [built]
 [509] ./client/pages/admin/statuses/search/index.jsx 6.15 kB {0} [built]
 [528] ./client/pages/main/index.jsx 400 bytes {2} [built]
 [529] ./client/pages/main/app.jsx 321 bytes {2} [built]
    + 541 hidden modules
[13:16:03] Finished 'webpack' after 13 s
[13:16:03] Starting 'build'...
[13:16:03] Finished 'build' after 2.96 μs
[13:16:03] Starting 'default'...
[13:16:03] Finished 'default' after 2.23 μs

```

**Comment by teheavy** [comment]
This happens when I'm running npm test

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.require.extensions.(anonymous function) [as .js] (/aqua/node_modules/lab/lib/coverage.js:37:28)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/aqua/test/lab/client-before.js:2:15)
    at Module._compile (module.js:413:34)
    at Object.require.extensions.(anonymous function) [as .js] (/aqua/node_modules/lab/lib/coverage.js:37:28)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /aqua/node_modules/lab/lib/cli.js:121:21
    at Array.forEach (native)
    at Object.internals.traverse.paths.forEach.testFiles [as traverse] (/aqua/node_modules/lab/lib/cli.js:117:15)
    at Object.exports.run (/aqua/node_modules/lab/lib/cli.js:62:31)
    at Object.<anonymous> (/aqua/node_modules/lab/bin/lab:50:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
npm ERR! Test failed.  See above for more details.
```

**Comment by jedireza** [comment]
I'm not sure what the problem is yet, but you can't reach the site because the server hasn't started

> `[13:15:51] [nodemon] app crashed - waiting for file changes before starting...`

And based on the second comment you left, it sounds like some dependencies (like `babel`) aren't taking affect.

What's the operating system? What version of node? Have you followed the README?

**Comment by teheavy** [comment]
I see, so I basically followed the README and I tried the same installation process on both OSX El Capitan and Ubuntu 14.04. My aqua version is the newest 7.0.2. 

Before, I thought it was because I was running nodeJS with Apache server, so I stopped the Apache server, but problem persists.

**Comment by jedireza** [comment]
What version of node?

**Comment by teheavy** [comment]
I'm using node v5.9.1 and npm 3.8.5.

**Comment by jedireza** [comment]
That's one problem, you should use node >= 8.x

https://github.com/jedireza/aqua/blob/ea085be912494561149e1899d68cb468e5e0d144/package.json#L17

**Comment by teheavy** [comment]
I see, problem solved! I didn't notice this problem! Thanks!
