### ISSUE TITLE
Problem running npm setup

### ISSUE THREAD

**Issue by tsyork** [jedireza/aqua#44]
When I run npm setup, I get the below error after entering values for the prompts (last prompt was for SMTP password). Any thoughts on what I could be doing wrong?

```
fs.js:491
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:491:11)
    at Object.fs.readFile (fs.js:262:6)
    at Array.Async.auto.createConfig (/Users/timyork/WebstormProjects/aqua/setup.js:98:12)
    at listener (/Users/timyork/WebstormProjects/aqua/node_modules/async/lib/async.js:582:42)
    at /Users/timyork/WebstormProjects/aqua/node_modules/async/lib/async.js:526:17
    at _arrayEach (/Users/timyork/WebstormProjects/aqua/node_modules/async/lib/async.js:78:13)
    at Immediate.taskComplete (/Users/timyork/WebstormProjects/aqua/node_modules/async/lib/async.js:525:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! aqua@3.3.0 setup: `./setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aqua@3.3.0 setup script './setup.js'.
npm ERR! This is most likely a problem with the aqua package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./setup.js
```

**Comment by jedireza** [comment]
Thanks for creating an issue and reporting this.

**Comment by jedireza** [comment]
This is fixed now.

**Comment by tsyork** [comment]
Thanks for the quick response!
