### ISSUE TITLE
$ npm run setup fail

### ISSUE THREAD

**Issue by GammaNu** [jedireza/aqua#49]
Hi,
I'm trying Aqua.
My running mongodb is launch like this : 
`$ sudo docker run -p 27017:27017 -d mongo`
i've done `$ npm install` and then `$ npm run setup`
and here what i've get : 
```
> aqua@3.3.2 setup /home/mb/dev/EBI
> ./setup.js

Project name: (Aqua) EBI
MongoDB URL: (mongodb://localhost:27017/aqua) mongodb://localhost:27017/EBI
Root user email: mb@gmail.com
Root user password: 
System email: (mb@gmail.com) 
SMTP host: (smtp.gmail.com) 
SMTP port: (465) 
SMTP username: (mb@gmail.com) 
SMTP password: 
/home/mb/dev/EBI/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/mb/dev/EBI/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mb/dev/EBI/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Linux 3.16.0-45-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "setup"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! aqua@3.3.2 setup: `./setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aqua@3.3.2 setup script './setup.js'.
npm ERR! This is most likely a problem with the aqua package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./setup.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls aqua
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mb/dev/EBI/npm-debug.log
```

And here is the `npm-debug.log` file : 

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@2.13.3
3 info using node@v0.12.7
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup aqua@3.3.2
6 info setup aqua@3.3.2
7 verbose unsafe-perm in lifecycle true
8 info aqua@3.3.2 Failed to exec setup script
9 verbose stack Error: aqua@3.3.2 setup: `./setup.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid aqua@3.3.2
11 verbose cwd /home/mb/dev/EBI
12 error Linux 3.16.0-45-generic
13 error argv "node" "/usr/bin/npm" "run" "setup"
14 error node v0.12.7
15 error npm  v2.13.3
16 error code ELIFECYCLE
17 error aqua@3.3.2 setup: `./setup.js`
17 error Exit status 1
18 error Failed at the aqua@3.3.2 setup script './setup.js'.
18 error This is most likely a problem with the aqua package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./setup.js
18 error You can get their info via:
18 error     npm owner ls aqua
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
Have i done something wrong or is it a Aqua issue ?

**Comment by jedireza** [comment]
Thanks for opening an issue. Let's try to fix that error with `bcrypt` first.

> at bindings (/home/mb/dev/EBI/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)

This sounds like an installation problem with the `bcrypt` module. Try running:

```bash
$ npm install bcrypt
```

Does that install without error? If so try running setup again. If that doesn't work are you willing to share some environment info such as:

```bash
$ npm version
```

**Comment by GammaNu** [comment]
I've just seen this https://github.com/jedireza/aqua/wiki/bcrypt-Installation-Trouble before reading your answer.
`$ npm install bcrypt --save` did the job (no error and now the `$ npm run setup` pass)
I just don't understand why bcrypt wasen't well installed first time with `$ npm install` in aqua folder.

In case this issue is reopen, here my `$ npm version` :
```
{ aqua: '3.3.2',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```
Thanks for your quick answer !

**Comment by jedireza** [comment]
Glad you got it worked out :+1:
