### ISSUE TITLE
$ npm test -> Error: Module did not self-register.

### ISSUE THREAD

**Issue by GammaNu** [jedireza/aqua#53]
Here is what i get when i run `$ npm test` : 

```
> aqua@3.3.2 test /home/mb/dev/EBI
> lab -t 100 -S -T ./test/transform.js -L --lint-options '{"extensions":[".js",".jsx"]}' ./test/client-before.js ./test/client/ ./test/client-after.js ./test/misc/ ./test/server/

Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/mb/dev/EBI/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mb/dev/EBI/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:34)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mb/dev/EBI/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mb/dev/EBI/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mb/dev/EBI/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mb/dev/EBI/node_modules/jsdom/lib/jsdom.js:10:27)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mb/dev/EBI/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mb/dev/EBI/test/client-before.js:1:13)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mb/dev/EBI/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/mb/dev/EBI/node_modules/lab/lib/cli.js:103:23
    at Array.forEach (native)
    at Object.internals.traverse (/home/mb/dev/EBI/node_modules/lab/lib/cli.js:99:19)
    at Object.exports.run (/home/mb/dev/EBI/node_modules/lab/lib/cli.js:48:29)
    at Object.<anonymous> (/home/mb/dev/EBI/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```
and here is my `$ npm version` :
```
{ aqua: '3.3.2',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```
Some idea ?

**Comment by GammaNu** [comment]
`$ rm -rf node_modules && npm install` fix it (i upgraded npm and node after my initial `$ npm install` to fix version warning). `$ npm rebuild` perhaps could work too.
