### ISSUE TITLE
Tests Not Running

### ISSUE THREAD

**Issue by clickslide** [jedireza/aqua#8]
Hello, 

Great project! Thank you for creating this example. 
I'm able to get the site up and running, but I can't get the tests to run.

I'm getting this error:
````
Error: Cannot find module 'react-router/modules/locations/TestLocation'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../aqua/test/client/pages/account/index.js:2:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js [as origLoader] (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../aqua/node_modules/lab/lib/coverage.js:50:26)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at .../aqua/node_modules/lab/lib/cli.js:95:23
    at Array.forEach (native)
    at Object.internals.traverse (.../aqua/node_modules/lab/lib/cli.js:91:19)
    at Object.exports.run (.../aqua/node_modules/lab/lib/cli.js:40:29)
    at Object.<anonymous> (.../aqua/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

````

````
{ aqua: '1.0.1',
  npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }
````

It seems that react-router isn't installed properly since there is no "modules" directory in the "node_modules/react-router" directory. What am I missing? 

Best,
Aaron

**Comment by justingreenberg** [comment]
Hi Aaron, I had same issue—tests were fixed in PR https://github.com/jedireza/aqua/pull/7 please retry with latest version of repo! :smile:

**Comment by jedireza** [comment]
:+1: Let us know if it still fails. If not, feel free to close this issue.

**Comment by clickslide** [comment]
Now the tests run, but I'm getting different errors.

````
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ........................................Warning: No route matches path "/admin". Make sure you have <Route path="/admin"> somewhere in your routes
..........
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..................................................
  ..........................
  ..........................Debug: internal, implementation, error 
    Error: Expected { Object (data, isBoom, ...) } to not exist
    at null.<anonymous> (.../node_modules/code/lib/index.js:142:17)
    at .../test/server/auth.js:86:45
    at transfer (.../node_modules/hapi/lib/auth.js:99:16)
    at Function.wrapped (.../node_modules/hapi/node_modules/hoek/lib/index.js:798:20)
    at Function.internals.response (.../node_modules/hapi/lib/reply.js:134:14)
    at reply (.../node_modules/hapi/lib/reply.js:67:22)
    at unauthenticated (.../node_modules/hapi-auth-cookie/lib/index.js:161:28)
    at validate (.../node_modules/hapi-auth-cookie/lib/index.js:114:28)
    at Object.scheme.authenticate (.../node_modules/hapi-auth-cookie/lib/index.js:179:13)
    at internals.Auth.test (.../node_modules/hapi/lib/auth.js:103:22)
    at Object.auth.test (.../node_modules/hapi/lib/plugin.js:62:79)
    at server.route.handler (.../test/server/auth.js:84:29)
    at Object.internals.handler (.../node_modules/hapi/lib/handler.js:94:36)
    at .../node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (.../node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (.../node_modules/hapi/lib/handler.js:22:22)
    at .../node_modules/hapi/lib/request.js:321:13
    at iterate (.../node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (.../node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at .../node_modules/hapi/node_modules/hoek/lib/index.js:781:22
    at process._tickDomainCallback (node.js:381:11)
....xxxx................
  ..................................................
  ...

Failed tests:

  931) Auth Plugin it takes over when the required role is missing:

      Expected undefined to match /insufficient scope/i

      at .../test/server/auth.js:278:53

  932) Auth Plugin it continues through pre handler when role is present:

      Expected 'You are being redirected...' to match /ok/i

      at .../test/server/auth.js:344:45

  933) Auth Plugin it takes over when the required group is missing:

      Expected undefined to match /permission denied/i

      at .../test/server/auth.js:413:53

  934) Auth Plugin it continues through pre handler when group is present:

      Expected 'You are being redirected...' to match /ok/i

      at .../test/server/auth.js:485:45
````

The "err" object in test/server/auth.js line 86 looks like the following.
````
{ [Error: Unauthorized]
  data: null,
  isBoom: true,
  output: 
   { statusCode: 401,
     payload: { statusCode: 401, error: 'Unauthorized' },
     headers: { 'WWW-Authenticate': 'cookie' } },
  reformat: [Function],
  message: 'Unauthorized',
  isMissing: true }
````
Please let me know if you can help with this.

**Comment by jedireza** [comment]
Would you be willing to share what operating system you're running and also what you get when you run:

```js
$ npm version
```

**Comment by clickslide** [comment]
npm version
````
{ aqua: '1.0.1',
  npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }
````
Running on OSX 10.10.2

**Comment by jedireza** [comment]
Interesting. That seems to be the same setup I'm running locally. I pushed some changes last night to upgrade `joi`. Let's make sure your `npm` cache is cleard, do a fresh clone and install and see what the test results show you.

**Comment by clickslide** [comment]
Great! The test run and pass now. Thanks for the support!

**Comment by jedireza** [comment]
great to hear :fireworks:
